### ISSUE TITLE
WooCommerce products <p class="cart">

### ISSUE THREAD

**Issue by csg79** [gruz0/remove-noreferrer#89]
Hi,
is it possible to remove the "noreferrer" in the <p class="cart"> link within a woocommerce product page for external/affiliates products?
The plugin works for everything else on my site, but not within the shop page. 
Thanks
Ali

**Comment by gruz0** [comment]
@csg79, hi!

Can you show me an example where plugin does not work?

**Comment by csg79** [comment]
Hi,

I actually figured out that it was because I was using another plugin that opens the link in a new tab, so I disabled that plugin for now.
Is there a way to open the link in a new tab and still remove noreferrer?

Thanks
Ali


________________________________

**Comment by gruz0** [comment]
You can modify your WooCommerce template to open links in the new page, I think. My plugin just removes `noreferrer` attribute from the links and does not modify something else.
